local base_colors = require("circus_show").get_colors()

if vim.g.colors_name then
    vim.cmd("hi clear")
end

vim.o.termguicolors = true
vim.g.colors_name = "circus_show"
vim.o.background = "dark"

vim.g.terminal_color_14 = "#87d7ff"
vim.g.terminal_color_6 = base_colors.cyan
vim.g.terminal_color_13 = "#ce9ffd"
vim.g.terminal_color_5 = base_colors.purple
vim.g.terminal_color_0 = base_colors.black
vim.g.terminal_color_8 = base_colors.gray
vim.g.terminal_color_1 = base_colors.red
vim.g.terminal_color_9 = "#ff5175"
vim.g.terminal_color_12 = "#88b0ff"
vim.g.terminal_color_4 = base_colors.blue
vim.g.terminal_color_11 = "#ffde85"
vim.g.terminal_color_3 = base_colors.yellow
vim.g.terminal_color_10 = "#b4e68f"
vim.g.terminal_color_2 = base_colors.green
vim.g.terminal_color_15 = base_colors.fg
vim.g.terminal_color_7 = base_colors.fg

vim.api.nvim_set_hl(0, "@lsp.typemod.variable.readonly", { link = "@constant" })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@function.builtin", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@lsp.type.variable", { link = "@variable" })
vim.api.nvim_set_hl(0, "@lsp.type.property", { link = "@property" })
vim.api.nvim_set_hl(0, "@property", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@lsp.type.parameter", { link = "@parameter" })
vim.api.nvim_set_hl(0, "@constant.builtin.c", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.type.namespace", { link = "@namespace" })
vim.api.nvim_set_hl(0, "@character.printf", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@lsp.type.interface", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.type.keyword", { link = "@keyword" })
vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@lsp.type.enum", { link = "@type" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@lsp.type.class", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.type.generic.rust", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@lsp.type.attributeBracket.rust", { link = "@punctuation.bracket.rust" })
vim.api.nvim_set_hl(0, "@punctuation.bracket.rust", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@lsp.type.builtinAttribute.rust", { link = "Function" })
vim.api.nvim_set_hl(0, "@odp.punctuation_token_bracket.rust", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@odp.punctuation_arguments_brackets.rust", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@variable.rust", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@type.qualifier.rust", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "GitSignsDeleteInline", { bg = "#6f2e2d" })
vim.api.nvim_set_hl(0, "GitSignsChangeInline", { bg = "#41483d" })
vim.api.nvim_set_hl(0, "GitSignsAddInline", { bg = "#3f534f" })
vim.api.nvim_set_hl(0, "GitSignsDeletePreview", { bg = "#502d30" })
vim.api.nvim_set_hl(0, "GitSignsAddPreview", { bg = "#43554d" })
vim.api.nvim_set_hl(0, "GitSignsUntrackedCursorLine", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "Title", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "GitSignsDeleteCursorLine", { fg = "#9a353d" })
vim.api.nvim_set_hl(0, "Number", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "GitSignsChangeCursorLine", { fg = "#948B60" })
vim.api.nvim_set_hl(0, "GitSignsAddCursorLine", { fg = "#109868" })
vim.api.nvim_set_hl(0, "@text.title.markdown", { bold = true, fg = base_colors.red })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineInformating", { link = "DiagnosticUnderlineInfo" })
vim.api.nvim_set_hl(0, "@keyword.operator", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@operator", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@constructor", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@markup.strong.markdown_inline", { bold = true, fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@markup.italic.markdown_inline", { fg = base_colors.purple, italic = true })
vim.api.nvim_set_hl(0, "@markup.raw.delimiter.markdown_inline", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@type.builtin.tsx", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@tag.attribute.tsx", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@punctuation.bracket.tsx", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@parameter.tsx", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@function.call.tsx", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@function.tsx", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@parameter.markdown_inline", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@punctuation.delimiter.markdown_inline", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "MasonWarning", { fg = base_colors.yellow, italic = true })
vim.api.nvim_set_hl(0, "MasonMuted", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "MasonHighlight", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "MasonMutedBlock", { bg = base_colors.fg, fg = base_colors.bg })
vim.api.nvim_set_hl(0, "MasonHighlightBlockBold", { bg = base_colors.purple, bold = true, fg = base_colors.bg })
vim.api.nvim_set_hl(0, "@constant.go", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@function.call.go", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@method.call.go", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@function.builtin.go", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@operator.go", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@type.go", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@type.builtin.go", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@field.go", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@include.ruby", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@function.call.ruby", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "xmlTagName", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "xmlTag", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "xmlAttrib", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@method.php", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@variable.go", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@function.builtin.php", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@namespace.php", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@constant.builtin.php", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@type.qualifier.php", { link = "@keyword.function" })
vim.api.nvim_set_hl(0, "BlinkCmpKindOperator", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "BlinkCmpKindEvent", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "BlinkCmpKindUnit", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "BlinkCmpKindTypeParameter", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "BlinkCmpKindStruct", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "BlinkCmpKindConstant", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "BlinkCmpKindEnumMember", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "BlinkCmpKindFile", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "BlinkCmpKindSnippet", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "BlinkCmpKindKeyword", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "BlinkCmpKindEnum", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "BlinkCmpKindValue", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "BlinkCmpKindProperty", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "BlinkCmpKindModule", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "BlinkCmpKindInterface", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "BlinkCmpKindClass", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "BlinkCmpKindField", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "BlinkCmpKindConstructor", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "BlinkCmpKindFunction", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "BlinkCmpKindMethod", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "BlinkCmpKindText", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "BlinkCmpSource", { fg = base_colors.comment })
vim.api.nvim_set_hl(0, "BlinkCmpLabelMatch", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "BlinkCmpLabelDeprecated", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "BlinkCmpLabel", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@punctuation.special", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@markup.list.unchecked", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@parameter.ruby", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@punctuation.bracket.ruby", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@symbol.ruby", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@odp.colon.ruby", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@lsp.typemod.enumMember.readonly.typescript", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@lsp.typemod.member.defaultLibrary.typescript", { link = "@function.typescript" })
vim.api.nvim_set_hl(0, "@function.typescript", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@lsp.mod.defaultLibrary.typescript", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.mod.readonly.typescript", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.typemod.enumMember.declaration.typescript", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@lsp.type.interface.typescript", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.type.enum.typescript", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@odp.property.function.typescript", { link = "@function.typescript" })
vim.api.nvim_set_hl(0, "@odp.operator.fat_arrow.typescript", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@variable.builtin.typescript", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@variable.typescript", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "SnacksPickerBufFlags", { link = "SnacksPickerDir" })
vim.api.nvim_set_hl(0, "SnacksPickerDir", { link = "Text" })
vim.api.nvim_set_hl(0, "@method.call.typescript", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "SnacksPickerCol", { fg = "#495162" })
vim.api.nvim_set_hl(0, "SnacksIndentScope", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "SnacksIndent", { fg = "#3c3c46" })
vim.api.nvim_set_hl(0, "@odp.puts.ruby", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@storageclass.rust", { link = "@keyword" })
vim.api.nvim_set_hl(0, "@operator.rust", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@function.macro.rust", { link = "Function" })
vim.api.nvim_set_hl(0, "@field.yaml", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@string.special.url.html", { underline = true })
vim.api.nvim_set_hl(0, "@type.qualifier.c", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@variable.parameter.c", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.readonly.c", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@text.uri.html", { fg = base_colors.green, underline = true })
vim.api.nvim_set_hl(0, "@odp.operator.splat.python", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@markup.quote.markdown", { fg = base_colors.comment })
vim.api.nvim_set_hl(0, "@constant.builtin.rust", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@parameter.go", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@method.call.php", { link = "@method.php" })
vim.api.nvim_set_hl(0, "@property.go", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary.lua", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "RenderMarkdownH1", { bold = true, fg = base_colors.red })
vim.api.nvim_set_hl(0, "@markup.heading.1.markdown", { bold = true, fg = base_colors.red })
vim.api.nvim_set_hl(0, "RenderMarkdownH1Bg", { bg = "#35252d" })
vim.api.nvim_set_hl(0, "@odp.class.lua", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@punctuation.bracket.luadoc", { fg = base_colors.comment })
vim.api.nvim_set_hl(0, "RenderMarkdownH2", { bold = true, fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@markup.heading.2.markdown", { bold = true, fg = base_colors.orange })
vim.api.nvim_set_hl(0, "RenderMarkdownH2Bg", { bg = "#362c2a" })
vim.api.nvim_set_hl(0, "@method.lua", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@keyword.operator.lua", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "RenderMarkdownH3", { bold = true, fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@markup.heading.3.markdown", { bold = true, fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "RenderMarkdownH3Bg", { bg = "#34312d" })
vim.api.nvim_set_hl(0, "@function.call.lua", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@function.builtin.lua", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "RenderMarkdownH4", { bold = true, fg = base_colors.green })
vim.api.nvim_set_hl(0, "@markup.heading.4.markdown", { bold = true, fg = base_colors.green })
vim.api.nvim_set_hl(0, "RenderMarkdownH4Bg", { bg = "#2c302d" })
vim.api.nvim_set_hl(0, "@constant.builtin.ruby", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@function.ruby", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "RenderMarkdownH5", { bold = true, fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@markup.heading.5.markdown", { bold = true, fg = base_colors.blue })
vim.api.nvim_set_hl(0, "RenderMarkdownH5Bg", { bg = "#2a2d39" })
vim.api.nvim_set_hl(0, "@odp.decorator.python", { link = "@function" })
vim.api.nvim_set_hl(0, "@odp.import_module.python", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@text.reference.markdown_inline", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "RenderMarkdownH6", { bold = true, fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@markup.heading.6.markdown", { bold = true, fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "RenderMarkdownH6Bg", { bg = "#293039" })
vim.api.nvim_set_hl(0, "@text.literal.markdown_inline", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "@method.call.python", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "RenderMarkdownH7", { bold = true, fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@markup.heading.7.markdown", { bold = true, fg = base_colors.purple })
vim.api.nvim_set_hl(0, "RenderMarkdownH7Bg", { bg = "#2e2a37" })
vim.api.nvim_set_hl(0, "@odp.interpolation.python", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@string.scss", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "SnacksIndentScope1", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "SnacksIndentScope2", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "SnacksIndentScope3", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "SnacksIndentScope4", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "SnacksIndentScope5", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "SnacksIndentScope6", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "SnacksIndentScope7", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@field.lua", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@keyword.lua", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@keyword.function.lua", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@operator.lua", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@parameter.lua", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "SpellRare", { fg = base_colors.red, sp = base_colors.red, undercurl = true })
vim.api.nvim_set_hl(0, "@punctuation.bracket.lua", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@odp.function_assignment.lua", { link = "@function" })
vim.api.nvim_set_hl(0, "SpellLocal", { fg = base_colors.red, sp = base_colors.red, undercurl = true })
vim.api.nvim_set_hl(0, "SpellCap", { fg = base_colors.red, sp = base_colors.red, undercurl = true })
vim.api.nvim_set_hl(0, "SpellBad", { fg = base_colors.red, sp = base_colors.red, undercurl = true })
vim.api.nvim_set_hl(0, "diffLine", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "diffNewFile", { fg = "#948B60" })
vim.api.nvim_set_hl(0, "diffFile", { fg = "#948B60" })
vim.api.nvim_set_hl(0, "WildMenu", { bg = base_colors.blue, fg = base_colors.black })
vim.api.nvim_set_hl(0, "Whitespace", { fg = base_colors.gray })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = base_colors.bg, fg = base_colors.gray })
vim.api.nvim_set_hl(0, "WinBarNC", { bg = base_colors.bg, fg = base_colors.fg })
vim.api.nvim_set_hl(0, "VisualNOS", { link = "Visual" })
vim.api.nvim_set_hl(0, "Visual", { bg = base_colors.selection })
vim.api.nvim_set_hl(0, "TermCursor", { bg = base_colors.purple })
vim.api.nvim_set_hl(0, "TabLineSel", { bg = base_colors.purple, fg = base_colors.bg })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = base_colors.bg, fg = base_colors.fg })
vim.api.nvim_set_hl(0, "TabLine", { bg = base_colors.bg })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = base_colors.bg, fg = base_colors.fg })
vim.api.nvim_set_hl(0, "IncSearch", { bg = base_colors.selection, fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "Search", { bg = base_colors.selection, fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "QuickFixLineNC", { bg = base_colors.bg })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = base_colors.bg })
vim.api.nvim_set_hl(0, "Question", { bg = base_colors.bg, fg = base_colors.gray })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#2c2c33" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#27272d" })
vim.api.nvim_set_hl(0, "PmenuSel", { bg = "#383840" })
vim.api.nvim_set_hl(0, "Pmenu", { bg = base_colors.picker_bg })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = base_colors.picker_bg, fg = base_colors.gray })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = base_colors.picker_bg })
vim.api.nvim_set_hl(0, "NormalNC", { bg = base_colors.bg, fg = base_colors.fg })
vim.api.nvim_set_hl(0, "Normal", { bg = base_colors.bg, fg = base_colors.fg })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "MsgSeparator", { link = "ModeMsg" })
vim.api.nvim_set_hl(0, "ModeMsg", { link = "Normal" })
vim.api.nvim_set_hl(0, "MsgArea", { link = "ModeMsg" })
vim.api.nvim_set_hl(0, "LineNrNC", { bg = "#35353d", fg = "#495162" })
vim.api.nvim_set_hl(0, "Substitute", { bg = base_colors.yellow, fg = base_colors.bg })
vim.api.nvim_set_hl(0, "SignColumnNC", { bg = "#35353d", fg = base_colors.gray })
vim.api.nvim_set_hl(0, "FoldedNC", { bg = "#35353d", fg = base_colors.gray })
vim.api.nvim_set_hl(0, "VertSplit", { bg = base_colors.bg, fg = base_colors.gray })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = base_colors.bg })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#005869", fg = base_colors.none })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#501b20", fg = base_colors.none })
vim.api.nvim_set_hl(0, "DiffChange", { bg = base_colors.none, fg = base_colors.none })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#003e4a", fg = base_colors.none })
vim.api.nvim_set_hl(0, "Directory", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "CursorLineNrNCQuickFix", { bg = base_colors.bg, fg = base_colors.purple })
vim.api.nvim_set_hl(0, "CursorLineNrNC", { bg = "#35353d", fg = base_colors.gray })
vim.api.nvim_set_hl(0, "CursorLineNr", { bg = base_colors.bg, fg = base_colors.purple })
vim.api.nvim_set_hl(0, "CursorLine", { bg = base_colors.bg })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = base_colors.gray })
vim.api.nvim_set_hl(0, "Cursor", { bg = base_colors.purple, fg = base_colors.bg })
vim.api.nvim_set_hl(0, "Conceal", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#35353d" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultError", { link = "DiagnosticError" })
vim.api.nvim_set_hl(0, "DiagnosticOk", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "@markup.list.checked", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@markup.list", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@markup.raw.delimiter", { fg = base_colors.gray })
vim.api.nvim_set_hl(0, "@markup.raw", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "@markup.link.url", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@markup.link.label", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@markup.math", { link = "Special" })
vim.api.nvim_set_hl(0, "@markup.heading", { bold = true, fg = base_colors.red })
vim.api.nvim_set_hl(0, "@markup.underline", { underline = true })
vim.api.nvim_set_hl(0, "@odp.base_constructor.python", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@markup.italic", { italic = true })
vim.api.nvim_set_hl(0, "@markup.strong", { bold = true, fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "qfFileName", { link = "Directory" })
vim.api.nvim_set_hl(0, "qfLineNr", { link = "LineNr" })
vim.api.nvim_set_hl(0, "Todo", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "Error", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "Italic", { italic = true })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "Underlined", { underline = true })
vim.api.nvim_set_hl(0, "@keyword.import", { link = "@keyword" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "Special", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "Typedef", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "Structure", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "StorageClass", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "Type", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "PreCondit", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "Macro", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "PreProc", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "Exception", { link = "Keyword" })
vim.api.nvim_set_hl(0, "Operator", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "Conditional", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "Function", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "Identifier", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "Boolean", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "Float", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "Character", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "String", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "Constant", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "Comment", { fg = base_colors.comment })
vim.api.nvim_set_hl(0, "@odp.plenary_function.lua", { link = "@function" })
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary.lua", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@type.scss", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@punctuation.special.markdown", { fg = base_colors.comment })
vim.api.nvim_set_hl(0, "@markup.raw.delimiter.markdown", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@label.markdown", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@markup.list.markdown", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@odp.punctuation.bracket.python", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@tag.attribute.vue", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@operator.vue", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@method.vue", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@function.call.typescript", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@method.typescript", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@parameter.typescript", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@punctuation.bracket.typescript", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@constructor.javascript", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@keyword.javascript", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@keyword.return.javascript", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@method.javascript", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@method.call.javascript", { link = "@method.javascript" })
vim.api.nvim_set_hl(0, "@variable.javascript", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@variable.builtin.javascript", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@odp.operator.fat_arrow.javascript", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@odp.jsxtag.javascript", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@odp.expression.punctuation.bracket.javascript", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@odp.function.punctuation.bracket.javascript", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@odp.punctuation.bracket.javascript", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@odp.statement.punctuation.bracket.javascript", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@lsp.type.class.javascript", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.type.namespace.javascript", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary.javascript", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@lsp.type.member.javascript", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@property.scss", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@punctuation.bracket.scss", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@text.strong.markdown_inline", { bold = true, fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@text.uri.markdown_inline", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@odp.nesting_selector.scss", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@odp.pseudo_class.scss", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@odp.selector.scss", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@odp.variable.scss", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@odp.vendor_prefix.scss", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@field.rust", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@conditional.python", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@constant.builtin.python", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@include.python", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@variable.builtin.python", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@punctuation.bracket.python", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@odp.constructor.python", { link = "@constructor" })
vim.api.nvim_set_hl(0, "@odp.decorator.function.python", { link = "@function" })
vim.api.nvim_set_hl(0, "@odp.function.builtin.python", { link = "@function.builtin" })
vim.api.nvim_set_hl(0, "@odp.import_from.python", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@operator.html", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@tag.attribute.html", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@odp.keyword.python", {})
vim.api.nvim_set_hl(0, "@keyword.function.python", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@odp.keyword.class.python", { link = "@keyword.function.python" })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@operator.toml", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@property.toml", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@odp.punctuation.special.python", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@constant.c", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@function.builtin.c", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@label.c", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@type.builtin.c", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@type.qualifier.java", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@type.builtin.java", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@lsp.type.macro.c", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary.c", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@odp.uri.comment", { link = "@text.uri.comment" })
vim.api.nvim_set_hl(0, "@function.call.yaml", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "@punctuation.bracket.yaml", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@parameter.yaml", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "@string.yaml", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "@label.json", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@odp.braces.json", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@odp.brackets.json", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = "#ecd79e" })
vim.api.nvim_set_hl(0, "RenderMarkdownTableHead", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#f87b94" })
vim.api.nvim_set_hl(0, "RenderMarkdownCodeInline", { bg = base_colors.picker_bg })
vim.api.nvim_set_hl(0, "@function.call", { link = "@function" })
vim.api.nvim_set_hl(0, "@function", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@attribute", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@type.qualifier", { link = "@type" })
vim.api.nvim_set_hl(0, "@type.definition", { link = "@type" })
vim.api.nvim_set_hl(0, "@type.builtin", { link = "@type" })
vim.api.nvim_set_hl(0, "@number.float", { link = "Float" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@boolean", { link = "Boolean" })
vim.api.nvim_set_hl(0, "@character.special", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@character", { link = "Character" })
vim.api.nvim_set_hl(0, "@string.special.url", { fg = base_colors.blue, italic = true, underline = true })
vim.api.nvim_set_hl(0, "@string.special.symbol", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@string.special", { link = "Special" })
vim.api.nvim_set_hl(0, "@string.escape", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@string.regex", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "@string", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "@label", { link = "Label" })
vim.api.nvim_set_hl(0, "@module", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@constant.macro", { link = "@constant" })
vim.api.nvim_set_hl(0, "@constant.builtin", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@variable.member", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@tag.delimiter", { link = "Delimiter" })
vim.api.nvim_set_hl(0, "@tag.attribute", { link = "@property" })
vim.api.nvim_set_hl(0, "@tag", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "LspDiagnosticsSignError", { link = "DiagnosticSignError" })
vim.api.nvim_set_hl(0, "LspDiagnosticsSignHint", { link = "DiagnosticSignHint" })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineWarning", { link = "DiagnosticUnderlineWarn" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = base_colors.yellow })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@keyword.exception", { link = "@keyword" })
vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#33373e" })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultInformation", { link = "DiagnosticInfo" })
vim.api.nvim_set_hl(0, "Bold", { bold = true })
vim.api.nvim_set_hl(0, "LspInfoBorder", { link = "FloatBorder" })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { link = "LspReferenceText" })
vim.api.nvim_set_hl(0, "Define", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "LspReferenceText", { bg = base_colors.selection })
vim.api.nvim_set_hl(0, "LspReferenceRead", { link = "LspReferenceText" })
vim.api.nvim_set_hl(0, "Include", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "Keyword", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "Label", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "Repeat", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineHint", { link = "DiagnosticUnderlineHint" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = "#aad9f0" })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextError", { link = "DiagnosticVirtualTextError" })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextInformation", { link = "DiagnosticVirtualTextInfo" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = "#afc7f5" })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextWarning", { link = "DiagnosticVirtualTextWarn" })
vim.api.nvim_set_hl(0, "RenderMarkdownTableRow", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "SpecialComment", { fg = base_colors.comment })
vim.api.nvim_set_hl(0, "RenderMarkdownDash", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "RenderMarkdownBullet", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@constant", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@keyword.return", { link = "@keyword" })
vim.api.nvim_set_hl(0, "@odp.pipe.ruby", { fg = base_colors.fg })
vim.api.nvim_set_hl(0, "@keyword.repeat", { link = "@keyword" })
vim.api.nvim_set_hl(0, "@keyword.conditional", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "Statement", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "@variable", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@label.ruby", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@keyword.function.ruby", { link = "@keyword.ruby" })
vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@function.macro", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@function.method", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#9a353d" })
vim.api.nvim_set_hl(0, "GitSignsUntracked", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultWarning", { link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultHint", { link = "DiagnosticHint" })
vim.api.nvim_set_hl(0, "LspDiagnosticsSignWarning", { link = "DiagnosticSignWarn" })
vim.api.nvim_set_hl(0, "LspDiagnosticsSignInformation", { link = "DiagnosticSignInfo" })
vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextHint", { link = "DiagnosticVirtualTextHint" })
vim.api.nvim_set_hl(0, "@function.method.call", { link = "@function.method" })
vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineError", { link = "DiagnosticUnderlineError" })
vim.api.nvim_set_hl(0, "@odp.curly_group_word.latex", { fg = base_colors.red })
vim.api.nvim_set_hl(0, "@odp.command.latex", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "@module.latex", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@markup.math.latex", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@keyword.return", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@keyword.repeat", { fg = base_colors.magenta })
vim.api.nvim_set_hl(0, "@keyword.conditional", { fg = base_colors.magenta })
vim.api.nvim_set_hl(0, "Statement", { fg = base_colors.magenta })
vim.api.nvim_set_hl(0, "@variable", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "Define", { fg = base_colors.magenta })
vim.api.nvim_set_hl(0, "Include", { fg = base_colors.magenta })
vim.api.nvim_set_hl(0, "Keyword", { fg = base_colors.magenta })
vim.api.nvim_set_hl(0, "Label", { fg = base_colors.magenta })
vim.api.nvim_set_hl(0, "Repeat", { fg = base_colors.purple })
vim.api.nvim_set_hl(0, "Removed", { fg = base_colors.statusred })
vim.api.nvim_set_hl(0, "Changed", { fg = base_colors.statusyellow })
vim.api.nvim_set_hl(0, "Added", { fg = base_colors.statusgreen })
vim.api.nvim_set_hl(0, "SpecialComment", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = base_colors.orange })
vim.api.nvim_set_hl(0, "@comment.documentation", { fg = base_colors.cyan })
vim.api.nvim_set_hl(0, "@constant", { fg = base_colors.magenta })
vim.api.nvim_set_hl(0, "CursorLineSign", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = base_colors.statusred })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = base_colors.statusyellow })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = base_colors.info_blue })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = base_colors.hint_blue })
vim.api.nvim_set_hl(0, "DiagnosticSignError", { fg = base_colors.statusred })
vim.api.nvim_set_hl(0, "DiagnosticSignWarn", { fg = base_colors.statusyellow })
vim.api.nvim_set_hl(0, "DiagnosticSignInfo", { fg = base_colors.info_blue })
vim.api.nvim_set_hl(0, "DiagnosticSignHint", { fg = base_colors.hint_blue })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = base_colors.statusred })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = base_colors.statusyellow })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = base_colors.info_blue })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = base_colors.hint_blue })
vim.api.nvim_set_hl(0, "HoverBorder", { fg = base_colors.bg_dark, blend = 100 })
vim.api.nvim_set_hl(0, "NonText", { fg = base_colors.gray, bg = base_colors.none })
vim.api.nvim_set_hl(0, "MatchParen", { fg = base_colors.blue })
vim.api.nvim_set_hl(0, "@lsp.type.comment", {})
vim.api.nvim_set_hl(0, "@comment.todo", { fg = base_colors.blue, bg = base_colors.blue_bg, bold = true })
vim.api.nvim_set_hl(0, "@comment.note", { fg = base_colors.cyan, bg = base_colors.blue_bg, bold = true })
vim.api.nvim_set_hl(0, "@comment.warning", { fg = base_colors.yellow, bg = base_colors.red_bg, bold = true })
vim.api.nvim_set_hl(0, "@comment.error", { fg = base_colors.red, bg = base_colors.red_bg, bold = true })
vim.api.nvim_set_hl(0, "@markup.strikethrough", { fg = base_colors.neutral_gray })
vim.api.nvim_set_hl(0, "SnacksBackdrop", { bg = "NONE" })
vim.api.nvim_set_hl(0, "SnacksDashboardIcon", { fg = base_colors.electric_pink, bold = true })
vim.api.nvim_set_hl(0, "SnacksDashboardHeader", { fg = base_colors.electric_pink, bold = true })
vim.api.nvim_set_hl(0, "SnacksPickerBoxCursorLine", { bg = base_colors.bg_light })
vim.api.nvim_set_hl(0, "SnacksPickerListCursorLine", { bg = base_colors.bg_light })
vim.api.nvim_set_hl(0, "SnacksPickerPathHidden", { fg = base_colors.neutral_gray })
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelpBorder", { fg = base_colors.bg_dark, blend = 100 })
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelp", { bg = base_colors.bg_dark })
vim.api.nvim_set_hl(0, "BlinkCmpDocBorder", { fg = base_colors.bg_dark, blend = 100 })
vim.api.nvim_set_hl(0, "BlinkCmpDoc", { bg = base_colors.bg_dark })
vim.api.nvim_set_hl(0, "BlinkCmpMenuBorder", { fg = base_colors.bg_dark, blend = 100 })
vim.api.nvim_set_hl(0, "BlinkCmpMenu", { bg = base_colors.bg_dark })
vim.api.nvim_set_hl(0, "RenderMarkdownCode", { bg = base_colors.bg_light })
vim.api.nvim_set_hl(0, "RenderMarkdownCheckboxNot", { fg = base_colors.statusred })
vim.api.nvim_set_hl(0, "RenderMarkdownChecked", { fg = base_colors.green })
vim.api.nvim_set_hl(0, "RenderMarkdownDiscarded", { fg = base_colors.neutral_gray, strikethrough = true })
vim.api.nvim_set_hl(0, "RenderMarkdownCode", { link = "@markup.raw" })
vim.api.nvim_set_hl(0, "GitSignsAdd", { link = "Added" })
vim.api.nvim_set_hl(0, "GitSignsChange", { link = "Changed" })
vim.api.nvim_set_hl(0, "GitSignsRemoved", { link = "Removed" })
vim.api.nvim_set_hl(0, "StatusLine", { bg = base_colors.bg_dark, fg = base_colors.fg })
vim.api.nvim_set_hl(0, "WinBar", { bg = base_colors.bg_dark, fg = base_colors.fg })
vim.api.nvim_set_hl(0, "FoldColumn", { fg = base_colors.mid_gray, bg = base_colors.picker_bg })
vim.api.nvim_set_hl(0, "SignColumn", { bg = base_colors.picker_bg, bold = true })
vim.api.nvim_set_hl(0, "LineNr", { fg = base_colors.gray, bg = base_colors.picker_bg })
